"""Make area name not unique

Revision ID: 67c85f0ec8ad
Revises: 1e7e2f436820
Create Date: 2025-01-05 12:26:39.395501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c85f0ec8ad'
down_revision = '1e7e2f436820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='areas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'areas', ['name'], unique=True)
    # ### end Alembic commands ###
