"""empty message

Revision ID: b93290db5109
Revises: 67c85f0ec8ad
Create Date: 2025-01-05 14:20:24.769048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93290db5109'
down_revision = '67c85f0ec8ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='cities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'cities', ['name'], unique=True)
    # ### end Alembic commands ###
